"""empty message

Revision ID: 1bdbe89ed72c
Revises: 8dd4b221d144
Create Date: 2023-01-19 00:47:00.369307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdbe89ed72c'
down_revision = '8dd4b221d144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('User_first_name_key', type_='unique')
        batch_op.drop_constraint('User_last_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('User_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('User_first_name_key', ['first_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
