"""empty message

Revision ID: 1ce5df551280
Revises: f1193206ebcd
Create Date: 2023-01-26 00:42:10.738612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce5df551280'
down_revision = 'f1193206ebcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(length=130),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('Wishlist_product_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('Wishlist_product_id_key', ['product_id'])

    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=130),
               existing_nullable=False)

    # ### end Alembic commands ###
