"""empty message

Revision ID: 1ce5df551280
Revises: f1193206ebcd
Create Date: 2023-01-26 00:42:10.738612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce5df551280'
down_revision = 'f1193206ebcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
