"""empty message

Revision ID: 302527ee6196
Revises: 1ce5df551280
Create Date: 2023-01-26 00:57:59.007228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302527ee6196'
down_revision = '1ce5df551280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:

        batch_op.drop_column('product_id')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(length=130), autoincrement=False, nullable=False))
        

    # ### end Alembic commands ###
