"""empty message

Revision ID: 3a35ab893854
Revises: 2c17f8136552
Create Date: 2023-01-25 23:35:52.273126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a35ab893854'
down_revision = '2c17f8136552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
