"""empty message

Revision ID: 455d350a4ac0
Revises: d5af53690527
Create Date: 2023-02-08 20:24:38.573282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455d350a4ac0'
down_revision = 'd5af53690527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subcategory_name', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_details', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sizes', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shipping_info', sa.String(length=500), nullable=True))
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('shipping_info')
        batch_op.drop_column('sizes')
        batch_op.drop_column('product_details')
        batch_op.drop_column('subcategory_name')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
