"""empty message

Revision ID: 548a3964549a
Revises: caf24c1b13f7
Create Date: 2023-01-18 21:34:45.696388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548a3964549a'
down_revision = 'caf24c1b13f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
