"""empty message

Revision ID: 6617cf1b21c9
Revises: 839aac676b3b
Create Date: 2023-02-03 17:35:24.057876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6617cf1b21c9'
down_revision = '839aac676b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('review_points')
        batch_op.drop_column('following')
        batch_op.drop_column('followers')
        batch_op.drop_column('profile_picture_path')

    # ### end Alembic commands ###
