"""empty message

Revision ID: 68a6402b77b7
Revises: d3853392d6f8
Create Date: 2023-01-18 22:04:49.429616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a6402b77b7'
down_revision = 'd3853392d6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'))

    # ### end Alembic commands ###
