"""empty message

Revision ID: 839aac676b3b
Revises: 5db895cfb842
Create Date: 2023-02-02 21:49:48.164438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839aac676b3b'
down_revision = '5db895cfb842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
