"""empty message

Revision ID: 90796a830e35
Revises: 3aa07bc1b91b
Create Date: 2023-02-02 00:30:50.198631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90796a830e35'
down_revision = '3aa07bc1b91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=500), nullable=False))
        batch_op.drop_column('filename2')
        batch_op.drop_column('filename5')
        batch_op.drop_column('picture_path2')
        batch_op.drop_column('picture_path1')
        batch_op.drop_column('picture_path3')
        batch_op.drop_column('picture_path4')
        batch_op.drop_column('filename4')
        batch_op.drop_column('filename3')
        batch_op.drop_column('filename1')
        batch_op.drop_column('picture_path5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_path5', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename1', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filename3', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename4', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('picture_path4', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('picture_path3', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('picture_path1', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('picture_path2', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename5', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename2', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('filename')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
