"""empty message

Revision ID: 9831467bd304
Revises: a6e3fb9c3046
Create Date: 2023-01-26 01:02:09.631601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9831467bd304'
down_revision = 'a6e3fb9c3046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=130),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"VideoUploads_video_id_seq"\'::regclass)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.String(length=130),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"VideoUploads_video_id_seq"\'::regclass)'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
