"""empty message

Revision ID: a54f8aa8e2f5
Revises: 60dc3a00ece5
Create Date: 2023-02-14 18:54:53.905442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54f8aa8e2f5'
down_revision = '60dc3a00ece5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sales',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=130), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('buyer_shipping', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sales')
    # ### end Alembic commands ###
