"""empty message

Revision ID: a6e3fb9c3046
Revises: 302527ee6196
Create Date: 2023-01-26 01:01:00.366794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e3fb9c3046'
down_revision = '302527ee6196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.drop_constraint('VideoUploads_product_id_key', type_='unique')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('Wishlist_product_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('Wishlist_product_id_key', ['product_id'])

    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(length=130), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('VideoUploads_product_id_key', ['product_id'])

    # ### end Alembic commands ###
