"""empty message

Revision ID: b068f49805d8
Revises: c1fc16d29771
Create Date: 2023-01-30 04:38:42.053338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b068f49805d8'
down_revision = 'c1fc16d29771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
