"""empty message

Revision ID: b14c6c582c24
Revises: 2ca9f388c436
Create Date: 2023-01-19 19:51:31.018760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14c6c582c24'
down_revision = '2ca9f388c436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
