"""empty message

Revision ID: b14c6c582c24
Revises: 2ca9f388c436
Create Date: 2023-01-19 19:51:31.018760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14c6c582c24'
down_revision = '2ca9f388c436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Wishlist', ['id'], ['user_id'])

    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=130), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Wishlist', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
