"""empty message

Revision ID: c1e4522427c6
Revises: 3a35ab893854
Create Date: 2023-01-26 00:34:16.913011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e4522427c6'
down_revision = '3a35ab893854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=130),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VideoUploads', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=130),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
