"""empty message

Revision ID: c3ab81b31cae
Revises: 455d350a4ac0
Create Date: 2023-02-08 21:36:18.254201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ab81b31cae'
down_revision = '455d350a4ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('subcategory_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.alter_column('subcategory_name',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('category_name',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
