"""empty message

Revision ID: dba6602e4ca7
Revises: e56f488c9ba5
Create Date: 2023-01-19 16:00:28.367375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba6602e4ca7'
down_revision = 'e56f488c9ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
