"""empty message

Revision ID: dbb21ae9dd45
Revises: 03c0125175f8
Create Date: 2023-01-25 22:31:50.434029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb21ae9dd45'
down_revision = '03c0125175f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
 
    # ### end Alembic commands ###
