"""empty message

Revision ID: e56f488c9ba5
Revises: 7c8371c33943
Create Date: 2023-01-19 01:09:04.682372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56f488c9ba5'
down_revision = '7c8371c33943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
