"""empty message

Revision ID: f1193206ebcd
Revises: 7df8b60df075
Create Date: 2023-01-26 00:41:03.987638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1193206ebcd'
down_revision = '7df8b60df075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
